plugins {
    id 'java'
    id 'org.springframework.boot' version '3.3.4'
    id 'io.spring.dependency-management' version '1.1.6'
}

group = 'com.digidive'
version = '0.0.1-SNAPSHOT'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

configurations {
    compileOnly {
        extendsFrom annotationProcessor
    }
}

repositories {
    mavenCentral()
}

dependencies {
    // Spring Boot MVC + JPA
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-web'

    // Flyway for database migrations
    implementation 'org.flywaydb:flyway-core'
    implementation 'org.flywaydb:flyway-database-postgresql'

    // Lombok for reducing boilerplate code
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'

    // Database driver (PostgreSQL)
    runtimeOnly 'org.postgresql:postgresql'

    // JWT for authentication
    implementation 'io.jsonwebtoken:jjwt-api:0.11.5'

    // Spring Boot testing dependencies
    testImplementation 'org.springframework.boot:spring-boot-starter-test'

    // Validation API
    implementation 'jakarta.validation:jakarta.validation-api'
}

tasks.named('test') {
    useJUnitPlatform()
}
