spring:
  flyway:
    enabled: 'true'
    locations: classpath:db/migration
    url: jdbc:postgresql://localhost:5432/${POSTGRESQL_DB_NAME}
    validate-on-migrate: 'true'
    user: ${POSTGRESQL_USERNAME}
    password: ${POSTGRESQL_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  application:
    name: DigiDive-Backend
  r2dbc:
    password: ${POSTGRESQL_PASSWORD}
    url: ${POSTGRESQL_LINK_REACTIVE}
    username: ${POSTGRESQL_USERNAME}
server:
  port: '8082'
